MONGODB:
  USER_NAME: ""
  PASSWORD: ""
BANKINFO: 
  COINALL:
    API_KEY: ""
    SECRET_KEY: ""
    PASS_PHRASE: ""
  BITBANK:
    API_KEY: ""
    SECRET_KEY: ""
  BITFLYER:
    API_KEY: ""
    SECRET_KEY: ""
  CRYPTOCOM:
    API_KEY: ""
    SECRET_KEY: ""
  COINCHECK:
    API_KEY: ""
    SECRET_KEY: ""
  COINMARKETCAP:
    API_KEY: "sandbox"
    SECRET_KEY: ""